# -*- coding: utf-8 -*-
"""Torre XX Expensas Mayo 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QndFXoaOdSh9_piTE1nx-EhQh4u7Azdo
"""

import pandas as pd
import numpy as np
!pip install pdfplumber
import pdfplumber
import matplotlib as mp

from google.colab import drive
pdf_path = "/content/drive/MyDrive/expensas torre 15/ARGERICH LIQUIDACION DE EXPENSAS MAYO 2026.pdf"

tablas = []

with pdfplumber.open(pdf_path) as pdf:
  for page in pdf.pages[1:]:
    tabla = page.extract_table()
    if tabla:
      df_temp = pd.DataFrame(tabla)
      tablas.append(df_temp)

df_completo = pd.concat(tablas, ignore_index=True)
df_completo.columns = [
    "Torre", "UF", "Depto", "Propietario", "%", "Saldo Anterior", "Pago Ordinario y Aysa",
    "Estacionamiento", "Deuda", "Exp Ordinarias", "Gastos Particulares", "Exp Extraordinarias", "Exp Ordinarias C",
    "Aysa","Estacionamiento2", "Interes","Total a Pagar"
    ]

df_limpio = df_completo[df_completo["Torre"].str.contains(r"^\d+$", na= False)].copy()
df_limpio["Propietario"] = df_limpio["Propietario"].str.replace("\n","")
identidades = df_limpio["Propietario"].unique()
mapeo_anonimos = {nombre: f"Propietario{i+1}" for i, nombre in enumerate(identidades)}
df_limpio["Propietario"] = df_limpio["Propietario"].map(mapeo_anonimos)

display(df_limpio.head(20))
df_limpio.to_excel("Liquidacion de Marzo 2026_anonimos.xlsx", index=False)

def limpimar_expensas(valor):
  if pd.isna(valor) or str(valor).strip() == "" or str(valor).strip() == ",":
    return 0.0
  texto = str(valor).strip()
  total_sum = 0.0
  parts = texto.strip("")

  for part in parts:
    part = part.strip()
    if not part:
      continue
    cleaned_part_value = 0.0
    if "," in part:
      part = part.replace(",","")
      try:
        cleaned_part_value = float(part)
      except ValueError:
        cleaned_part_value = 0.0
    elif "." in part:
      sub_part = part.split(".")
      if len(sub_part[-1]) == 2:
        try:
          cleaned_part_value = float(part)
        except ValueError:
          cleaned_part_value = 0.0
      elif len(sub_part[-1]) == 3:
        try:
          cleaned_part_value = float(part)
        except ValueError:
          cleaned_part_value = 0.0
      else:
        try:
          cleaned_part_value = float(part)
        except ValueError:
          cleaned_part_value = 0.0

    else:
      try:
        cleaned_part_value = float(part)/100
      except ValueError:
        cleaned_part_value = 0.0

    total_sum += cleaned_part_value
    return total_sum

def limpiar_pagos_expensas(valor):
    if pd.isna(valor) or str(valor).strip() == "" or valor == ",":
        return 0.0

    texto = str(valor).strip()

    # 1. PROGRAMACIÓN DEFENSIVA: Si el número es negativo, le sacamos el signo menos
    if texto.startswith('-'):
        texto = texto.replace('-', '')

    # 2. Si tiene comas de miles (Hojas 3 y 4), las removemos
    if ',' in texto:
        texto = texto.replace(',', '')
        return float(texto)

    # 3. Para la Hoja 5: Si tiene un punto que actúa como miles (ej: 37.940)
    elif '.' in texto:
        partes = texto.split('.')
        if len(partes[1]) == 3:  # Es un punto de miles
            texto = texto.replace('.', '')
            return float(texto)
        else:
            return float(texto)

    # 4. Si no tiene separadores (ej: "37940"), lo convertimos directo a flotante positivo
    try:
        return float(texto)
    except ValueError:
        return 0.0

def limpiar_deuda_bruta(valor):
    if pd.isna(valor) or str(valor).strip() == "" or valor == ",":
        return 0.0

    texto = str(valor).strip()
    # 1. Detectamos si el número empieza con un signo menos
    es_negativo = False
    if texto.startswith('-'):
        es_negativo = True
        texto = texto.replace('-', '') # Se lo sacamos para limpiarlo sin problemas

    # 2. Formato estándar con comas y puntos (Hojas 3 y 4, ej: "139,575.00")
    if ',' in texto and '.' in texto:
        if texto.find(',') < texto.find('.'):
            texto = texto.replace(',', '')
            monto = float(texto)

    # 3. Formato de la Hoja 5 (ej: "217.960.38" o puntos de miles "139.575")
    elif '.' in texto:
        partes = texto.split('.')
        if len(partes[1]) == 3:  # Es un punto de miles (ej: 139.575)
            texto = texto.replace('.', '')
            monto = float(texto)
        else:
            try:
                monto = float(texto)
            except ValueError:
                texto_plano = texto.replace('.', '')
                monto = float(texto_plano) / 100.0

    # 4. Si no tiene ningún separador
    else:
        try:
            monto = float(texto)
        except ValueError:
            monto = 0.0

    # 5. Si detectamos que originalmente era negativo (saldo a favor)...
    if es_negativo:
        return 0.0  # Lo ignoramos por completo convirtiéndolo en cero
    else:
        return monto  # Si es positivo (deuda real), devolvemos el monto

def limpiar_estacionamiento2(valor):
    # 1. Atajamos nulos, vacíos o celdas con solo una coma
    if pd.isna(valor) or str(valor).strip() == "" or valor == ",":
        return 0.0

    texto = str(valor).strip()

    # 2. Si viene con formato tradicional de miles y decimales (ej: "15,000.00")
    if ',' in texto and '.' in texto:
        if texto.find(',') < texto.find('.'):
            texto = texto.replace(',', '')
            return float(texto)

    # 3. Si tiene puntos (ej: "15.000" o "125.000")
    elif '.' in texto:
        partes = texto.split('.')
        # Si después del punto hay 3 dígitos, era un punto de miles. Lo borramos.
        if len(partes[1]) == 3:
            texto = texto.replace('.', '')
            return float(texto)
        # Si tiene 2 dígitos o menos, es un decimal real (ej: 15000.00)
        else:
            try:
                return float(texto)
            except ValueError:
                return 0.0

    # 4. Si tiene comas pero no puntos, a veces el lector confunde el punto de miles por coma
    elif ',' in texto:
        partes = texto.split(',')
        if len(partes[1]) == 3: # ej: "15,000"
            texto = texto.replace(',', '')
            return float(texto)
        else:
            try:
                # Si era "15000,00" (formato latino), cambiamos la coma por punto
                texto = texto.replace(',', '.')
                return float(texto)
            except ValueError:
                return 0.0

    # 5. Si es un número limpio sin separadores (ej: "15000")
    try:
        return float(texto)
    except ValueError:
        return 0.0

def limpiar_intereses(valor):
    # 1. Atajamos vacíos o valores nulos y los volvemos 0.0
    if pd.isna(valor) or str(valor).strip() == "" or valor == ",":
        return 0.0

    texto = str(valor).strip()

    # 2. Por seguridad, si el PDF leyó un signo menos por error, lo eliminamos
    if texto.startswith('-'):
        texto = texto.replace('-', '')

    # 3. Formato tradicional con comas de miles y puntos (ej: "1,500.00")
    if ',' in texto and '.' in texto:
        if texto.find(',') < texto.find('.'):
            texto = texto.replace(',', '')
            return float(texto)

    # 4. Formato de la Hoja 5: si tiene un punto que actúa como miles (ej: "3.889")
    elif '.' in texto:
        partes = texto.split('.')
        if len(partes[1]) == 3: # Si tiene 3 números a la derecha, es punto de miles
            texto = texto.replace('.', '')
            return float(texto)
        else:
            try:
                return float(texto)
            except ValueError:
                return 0.0

    # 5. Si viene como un número entero pelado (ej: "5000")
    try:
        return float(texto)
    except ValueError:
        return 0.0

df_limpio['Saldo Anterior'] = df_limpio['Saldo Anterior'].astype(str)
df_limpio['Saldo_Anterior_Limpio'] = df_limpio['Saldo Anterior'].apply(limpiar_expensas)
saldo_anterior = df_limpio['Saldo_Anterior_Limpio'].sum()
resultado_formateado = f"${saldo_anterior:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
print("Suma total de saldo anterior:", resultado_formateado)

df_limpio["Pago Ordinario y Aysa"] = df_limpio["Pago Ordinario y Aysa"].astype(str)
df_limpio["Pago_Ordinario_y_Aysa_Limpio"] = df_limpio["Pago Ordinario y Aysa"].apply(limpiar_pagos_expensas)
pago_ordinario_y_aysa = df_limpio["Pago_Ordinario_y_Aysa_Limpio"].sum()
resultado_formateado = f"${pago_ordinario_y_aysa:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de pago ordinario y aysa:", resultado_formateado)

df_limpio["Estacionamiento"] = df_limpio["Estacionamiento"].astype(str)
df_limpio["Estacionamiento"] = df_limpio["Estacionamiento"].apply(limpiar_pagos_expensas)
estacionamiento_limpio = df_limpio["Estacionamiento"].sum()
resultado_formateado = f"${estacionamiento_limpio:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de estacionamiento",resultado_formateado)

df_limpio["Deuda"] = df_limpio["Deuda"].astype(str)
df_limpio["Deuda_Bruta_Limpia"] = df_limpio["Deuda"].apply(limpiar_deuda_bruta)
deuda_bruta_total = df_limpio["Deuda_Bruta_Limpia"].sum()
resultado_formateado = f"${deuda_bruta_total:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Deuda Total Neta (Sin saldos a favor):", resultado_formateado)

df_limpio["Exp Ordinarias"] = df_limpio["Exp Ordinarias"].astype(str)
df_limpio["Exp Ordinarias"] = df_limpio["Exp Ordinarias"].apply(limpiar_expensas)
exp_ordinarias_limpias = df_limpio["Exp Ordinarias"].sum()
resultado_formateado = f"${exp_ordinarias_limpias:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de expensas ordinarias:", resultado_formateado)

df_limpio["Exp Extraordinarias"] = df_limpio["Exp Extraordinarias"].astype(str)
df_limpio["Exp Extraordinarias"] = df_limpio["Exp Extraordinarias"].apply(limpiar_expensas)
exp_extraordinarias_limpias = df_limpio["Exp Extraordinarias"].sum()
resultado_formateado = f"${exp_extraordinarias_limpias:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de expensas extraordinarias:", resultado_formateado)

df_limpio["Gastos Particulares"] = df_limpio["Gastos Particulares"].astype(str)
df_limpio["Gastos Particulares"] = df_limpio["Gastos Particulares"].apply(limpiar_expensas)
gastos_particulares_limpios = df_limpio["Gastos Particulares"].sum()
resultado_formateado = f"${gastos_particulares_limpios:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de gastos particulares:", resultado_formateado)

df_limpio["Aysa"] = df_limpio["Aysa"].astype(str)
df_limpio["Aysa"] = df_limpio["Aysa"].apply(limpiar_expensas)
aysa_limpia = df_limpio["Aysa"].sum()
resultado_formateado = f"${aysa_limpia:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de aysa:", resultado_formateado)

df_limpio["Estacionamiento2"] = df_limpio["Estacionamiento2"].astype(str)
df_limpio["Estacionamiento2"] = df_limpio["Estacionamiento2"].apply(limpiar_estacionamiento2)
estacionamiento2_limpio = df_limpio["Estacionamiento2"].sum()
resultado_formateado = f"${estacionamiento2_limpio:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de estacionamiento2:", resultado_formateado)

df_limpio["Interes"] = df_limpio["Interes"].astype(str)
df_limpio["Interes"] = df_limpio["Interes"].apply(limpiar_intereses)
interes_limpio = df_limpio["Interes"].sum()
resultado_formateado = f"${interes_limpio:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("Suma total de interes:", resultado_formateado)

df_limpio['Total a Pagar'] = df_limpio['Total a Pagar'].astype(str)
df_limpio['TOTAL A PAGAR_LIMPIO'] = df_limpio['Total a Pagar'].apply(limpiar_expensas)
total_a_pagar_limpio = df_limpio["TOTAL A PAGAR_LIMPIO"].sum()
resultado_formateado = f"${total_a_pagar_limpio:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
print("Suma total a pagar:", resultado_formateado)

total_unidades = len(df_limpio)
print(f"Total de unidades: {total_unidades}")

df_limpio["Deuda"] = df_limpio["Deuda"].astype(str)
df_limpio["Deuda_Bruta_Limpia"] = df_limpio["Deuda"].apply(limpiar_deuda_bruta)
cantidad_deudores = (df_limpio["Deuda_Bruta_Limpia"] > 1000).sum()
print(f"Cantidad de deudores reales: {cantidad_deudores}")

porcentaje_morosidad = (cantidad_deudores / total_unidades) * 100
print(f"Porcentaje de morosidad: {porcentaje_morosidad:.2f}%")

deuda_total_consorcio = df_limpio["Deuda_Bruta_Limpia"].sum()
top_5_deudores = df_limpio.nlargest(5, "Deuda_Bruta_Limpia")[['Propietario', 'UF', 'Deuda_Bruta_Limpia']].copy()
top_5_deudores["Peso_%"] = (top_5_deudores["Deuda_Bruta_Limpia"] / deuda_total_consorcio) * 100

print("======= LOS 5 PRINCIPALES DEUDORES =======\n")

for idx, fila in top_5_deudores.iterrows():
    monto_formateado = f"${fila['Deuda_Bruta_Limpia']:,.2f}".replace(",","x").replace(".",",").replace("x",".")
    print(f"- {fila['Propietario']} ({fila['UF']}): {monto_formateado} -> Representa el {fila['Peso_%']:.2f}%")

print("\n")

suma_top_5 = top_5_deudores["Deuda_Bruta_Limpia"].sum()
peso_total_top_5 = top_5_deudores["Peso_%"].sum()
suma_formateada = f"${suma_top_5:,.2f}".replace(",","x").replace(".",",").replace("x",".")

print(f"- SUMA TOTAL DEL TOP 5: {suma_formateada} ")
print(f"- PESO EN CONJUNTO SOBRE EL TOTAL: {peso_total_top_5:.2f}%")

top_3_deudores = df_limpio.nlargest(3, "Deuda_Bruta_Limpia")[['Propietario', 'UF', 'Deuda_Bruta_Limpia']].copy()

top_3_deudores["Peso_%"] = (top_3_deudores["Deuda_Bruta_Limpia"] / deuda_total_consorcio) * 100

print("=== LOS 3 PRINCIPALES DEUDORES ===\n")

for idx, fila in top_3_deudores.iterrows():
    monto_formateado = f"${fila['Deuda_Bruta_Limpia']:,.2f}".replace(",","x").replace(".",",").replace("x",".")
    print(f"- {fila['Propietario']} ({fila['UF']}): {monto_formateado} -> Representa el {fila['Peso_%']:.2f}%")

suma_top_3 = top_3_deudores["Deuda_Bruta_Limpia"].sum()
peso_total_top_3 = top_3_deudores["Peso_%"].sum()
suma_formateada = f"${suma_top_3:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print("\n")
print(f"- SUMA TOTAL DEL TOP 3: {suma_formateada}")
print(f"- PESO EN CONJUNTO SOBRE EL TOTAL: {peso_total_top_3:.2f}%")

import matplotlib.pyplot as plt

deuda_total_consorcio = df_limpio["Deuda_Bruta_Limpia"].sum()
cantidad_total_ufs = len(df_limpio)
cantidad_deudores = (df_limpio["Deuda_Bruta_Limpia"] > 0).sum()

top_5_df = df_limpio.nlargest(5, "Deuda_Bruta_Limpia")
suma_top_5 = top_5_df["Deuda_Bruta_Limpia"].sum()

resto_deuda = deuda_total_consorcio - suma_top_5

porcentaje_deudores_uf = (cantidad_deudores / cantidad_total_ufs) * 100
porcentaje_peso_top5 = (suma_top_5 / deuda_total_consorcio) * 100

print("=== DIAGNÓSTICO DE MOROSIDAD ACUMULADA ===")
print(f"• Total de Unidades Funcionales: {cantidad_total_ufs}")
print(f"• Cantidad de Deudores Activos: {cantidad_deudores} ({porcentaje_deudores_uf:.1f}% del edificio)")
print(f"• Peso del TOP 5: Representan el {porcentaje_peso_top5:.1f}% de toda la deuda pendiente.")
print("="*42 + "\n")

porciones = [suma_top_5, resto_deuda]
etiquetas = [f'\nTop 5 Grandes Deudores\n',
             f'Resto de Deudores\n']

colores = ['#1B365D', '#A2B5CD']
explode = (0.08, 0)

plt.figure(figsize=(8, 6))
plt.pie(porciones,
        explode=explode,
        labels=etiquetas,
        colors=colores,
        autopct='%1.1f%%', # Muestra el porcentaje interno automático de la porción
        shadow=True,
        startangle=140,
        textprops={'fontsize': 11, 'weight': 'bold'})

plt.title("Distribución y Concentración de la Deuda Total", fontsize=14, pad=20, weight='bold', color='#1B365D')
plt.axis('equal')  # Asegura que la torta sea un círculo perfecto

plt.show()

datos_historicos = [
    {"Mes": "2025-08", "Deuda_Total": 8767905.00, "Cantidad_Deudores": 24},
    {"Mes": "2025-09", "Deuda_Total": 9665531.00, "Cantidad_Deudores": 31},
    {"Mes": "2025-10", "Deuda_Total": 9038182.00, "Cantidad_Deudores": 23},
    {"Mes": "2025-11", "Deuda_Total": 9359896.00, "Cantidad_Deudores": 19},
    {"Mes": "2025-12", "Deuda_Total": 12767672.00, "Cantidad_Deudores": 24},
    {"Mes": "2026-01", "Deuda_Total": 13238040.00, "Cantidad_Deudores": 24},
    {"Mes": "2026-02", "Deuda_Total": 14290165.00, "Cantidad_Deudores": 27},
    {"Mes": "2026-03", "Deuda_Total": 14445476.00, "Cantidad_Deudores": 25},
    {"Mes": "2026-04", "Deuda_Total": 16157097.00, "Cantidad_Deudores": 31},
    {"Mes": "2026-05", "Deuda_Total": 18190444.00, "Cantidad_Deudores": 31},
]

df_historico = pd.DataFrame(datos_historicos)

df_historico["Mes"] = pd.to_datetime(df_historico["Mes"])
display(df_historico)

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

fig, (ax1) = plt.subplots(1, figsize=(10, 6), sharex=True)

ax1.plot(df_historico["Mes"], df_historico["Deuda_Total"], color='#D9383A', marker='o', linewidth=2.5, label="Deuda Acumulada ($)")
ax1.fill_between(df_historico["Mes"], df_historico["Deuda_Total"], color='#D9383A', alpha=0.1)
ax1.set_title('Evolución de la Deuda Bruta ($)', fontsize=10, loc='left', pad=12, weight='bold')
ax1.set_ylabel('')
ax1.grid(True, linestyle='--', alpha=0.5)
ax1.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x)).replace(",", ".")))

for i, row in df_historico.iterrows():
    texto_valor = f"${row['Deuda_Total']/1_000_000:.1f}M"

    ax1.annotate(texto_valor,
                 (row['Mes'], row['Deuda_Total']),
                 textcoords="offset points",
                 xytext=(0, 10),
                 ha='center',
                 fontsize=9, weight='bold', color='#B32426')

ax1.set_ylim(df_historico["Deuda_Total"].min() * 0.95, df_historico["Deuda_Total"].max() * 1.08)
plt.suptitle('MOROSIDAD HISTÓRICA \n', fontsize=14, weight='bold', y=0.98)
fig.autofmt_xdate()
plt.tight_layout()
plt.show()

fig, (ax2) = plt.subplots(1, figsize=(10, 6), sharex=True)
barras = ax2.bar(df_historico["Mes"], df_historico["Cantidad_Deudores"], color='#2B6CB0', alpha=0.8, width=15, label="Propietarios Morosos")

ax2.set_title('\n Cantidad de Propietarios Morosos Activos', fontsize=10, loc='left', pad=12, weight='bold')
ax2.set_ylabel('Cantidad de U.F.')
ax2.grid(True, linestyle='--', alpha=0.5)

ax2.bar_label(barras,
              padding=4,
              fontsize=10,
              weight='bold',
              color='#1A446C')

ax2.set_ylim(0, df_historico["Cantidad_Deudores"].max() * 1.15)

plt.tight_layout()
plt.show()